### ISSUE TITLE
how to automatically run the webdriver before running the program?

### ISSUE THREAD

**Issue by centuryhopper** [stevepryde/thirtyfour#173] opened 2023-07-25 22:04 UTC
Right now with the code example shown in the docs, you have to manually run the webdriver in the terminal before you run the rust program. How can we automate opening and closing the webdriver as we run the rust program? I see people ask something similar and that a selenium webdriver manager seems to be the solution. However, I couldn't find any instructions for how to set that up. The readme file on that page wasn't clear. Thanks.

**Comment by 0elek** [comment] 2023-08-20 19:44
You can just make a sh script 
```
./chromedriver && cargo run --release
```
it works fine for me

**Comment by 0elek** [comment] 2023-08-20 19:45
https://github.com/stevepryde/thirtyfour/issues/172#issuecomment-1635092658

**Comment by stevepryde** [comment] 2024-01-05 23:48
duplicate of #172

**Closed by stevepryde** 2024-01-05 23:48 UTC
