### ISSUE TITLE
geckodriver fails 

### ISSUE THREAD

**Issue by Tockra** [stevepryde/thirtyfour#44] opened 2021-04-23 16:32 UTC
Hi Guys,

I found several scenerios where the geckdodriver becomes a state, where I can't create a new connection.
These cases I found:
- If I exit the programm with cmd + c while a find_element action is active.
- If you create a driver with new_with_timeout() and you got the timeout while find_element(s) .

In the cases after the application restarts you get these exception:
```bash
2021-04-23 18:31:30,333 INFO  [app] Connect to WebDriver
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SessionNotCreated(WebDriverErrorInfo { status: 500, error: "", value: WebDriverErrorValue { message: "Session is already started", error: Some("session not created"), stacktrace: Some(""), data: None } })', src\main.rs:20:80
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\item_tracker.exe ./` (exit code: 101)
```

T

**Comment by stevepryde** [comment] 2021-04-23 22:35
Can you please provide code samples to reproduce these errors? Thanks

**Comment by audioXD** [comment] 2021-07-03 18:26
I think this happens because it doesn't cleans after itself. AKA an error occurs and you don't close it. 
Because the session hasn't been closed you get this error when connecting to it again.

**Comment by stevepryde** [comment] 2021-08-06 11:19
As per the above comment. This is normal geckodriver behaviour.

**Closed by stevepryde** 2021-08-06 11:19 UTC
