### ISSUE TITLE
Auto setup `chromedriver` and `geckodriver`

### ISSUE THREAD

**Issue by itsezc** [stevepryde/thirtyfour#172] opened 2023-07-14 00:07 UTC
Perhaps this is an upstream issue, if it is, please feel free to close it.

To improve DX (decrease friction) with setting up thirtyfour, it'd be great if we could auto setup chrome driver and firefox drivers, there are some crates that makes it easier i.e. https://crates.io/crates/chromedriver-autoinstaller

We could take the same approach for geckodriver and potentially for WebKit (for MacOS) too.

**Comment by stevepryde** [comment] 2023-07-14 00:37
Have a look at Selenium Manager. It should be able to take care of this for you.

https://github.com/SeleniumHQ/selenium/tree/trunk/rust

**Comment by stevepryde** [comment] 2024-04-23 10:59
Duplicate of #127

**Closed by stevepryde** 2024-04-23 10:59 UTC
