### ISSUE TITLE
How to get network request

### ISSUE THREAD

**Issue by servonlewis** [stevepryde/thirtyfour#76] opened 2021-11-02 22:58 UTC
Hello all,

Is there a way to get a list of all network request on a webpage?

My main goal is to extract a specific request's header value.

**Comment by stevepryde** [comment] 2021-11-04 12:09
Not directly in selenium 3.x, but have a look at CDP (Chrome Devtools Protocol) which allows you to do this in Chromium-based browsers: https://chromedevtools.github.io/devtools-protocol/

I believe there may also be support in Firefox for CDP, via the RemoteProtocol: https://wiki.mozilla.org/WebDriver/RemoteProtocol

Selenium 4.x will also support this particular feature, though I'm not yet sure if it will use CDP or whether the WebDriver spec is being updated (I suspect it's CDP). There is some CDP support in `thirtyfour` already, but there's still a lot that could be added to make it better. Also see this issue which may be related: https://github.com/stevepryde/thirtyfour/issues/55

**Comment by stevepryde** [comment] 2022-12-19 01:04
Duplicate of #55

**Closed by stevepryde** 2022-12-19 01:04 UTC
Labels: help wanted
